Add Baidu, Tencent
ethereum-wallets/ethereum-wallet-list pull request #6
Opened 2018-09-19 13:32 UTC by p0s

2018-09-19 14:02 UTC, ligi requested changes
imToken uses QQ - and this PR removes it - my CI is not happy about this. And please all new ones upper-case to indicate these are constants not free text and to map it to enum

2018-09-20 05:07 UTC, p0s commented
I removed QQ on purpose, because it's wrong. It should be called TENCENT instead, which I added.

2018-09-20 08:35 UTC, ligi approved these changes

2018-09-20 08:44 UTC, ligi commented
Thanks - added this via a6de118bbd0fa466dbd40ff4e6cc4a0d52797991 to adapt to changes in master and combine with #5 so the CI is happy (#5 and #6 needed to go together - otherwise the CI fails)

2018-09-20 08:44 UTC, closed without merging